package io.github.flowerjvm.flower.action.runtime.audit;

public enum AuditEventType {
    ACTION_PROPOSED,
    ACTION_RESOLVED,
    VALIDATION_COMPLETED,
    POLICY_EVALUATED,
    POLICY_REEVALUATED,
    PRE_EXECUTION_CHECKED,
    DRY_RUN_COMPLETED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_EXPIRED,
    ACTION_EXECUTION_STARTED,
    ACTION_EXECUTION_DEFERRED,
    ACTION_EXECUTION_COMPLETED,
    ACTION_EXECUTION_FAILED,
    ACTION_EXECUTION_CANCELLED,
    ACTION_RUNTIME_FAILED,
    ACTION_DENIED,
    ACTION_DUPLICATE
}
