ALTER TABLE action_run ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS request_channel VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS proposer_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS external_operation_id VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS external_operation_metadata_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS result_code VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE action_run ADD COLUMN IF NOT EXISTS result_retry_disposition VARCHAR(32) NULL;
